-- Strava ML Demo Environment Setup
-- This script sets up the complete environment for the Strava ML demo

--Set Context
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE ROLE STRAVA_DEMO_ADMIN;
GRANT ROLE STRAVA_DEMO_ADMIN TO ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE STRAVA_DEMO_ADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE STRAVA_DEMO_ADMIN;

--Switch to new role
USE ROLE STRAVA_DEMO_ADMIN;

--Create Warehouse
CREATE OR REPLACE WAREHOUSE STRAVA_DEMO_WH
WAREHOUSE_SIZE = XSMALL
AUTO_RESUME = TRUE 
INITIALLY_SUSPENDED = FALSE
AUTO_SUSPEND = 150;

USE WAREHOUSE STRAVA_DEMO_WH;



-- Create a new database for the sample data
CREATE OR REPLACE DATABASE STRAVA_DEMO_SAMPLE;

-- Create schema for raw data
CREATE OR REPLACE SCHEMA STRAVA_DEMO_SAMPLE.RAW_DATA;


-- Switch to new context
USE DATABASE STRAVA_DEMO_SAMPLE;
USE SCHEMA STRAVA_DEMO_SAMPLE.RAW_DATA;

-- Create a file format for CSV files that have a header row
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE;

-- Create an internal stage to temporarily store the data files before loading
CREATE OR REPLACE STAGE STRAVA_DEMO_STAGE
    FILE_FORMAT = CSV_FORMAT;


-- Create the ACTIVITIES table
CREATE OR REPLACE TABLE ACTIVITIES (
    ACTIVITY_ID INTEGER,
    ATHLETE_ID INTEGER,
    ACTIVITY_TYPE VARCHAR(50),
    START_DATE_LOCAL TIMESTAMP,
    DISTANCE_METERS FLOAT,
    MOVING_TIME_SEC INTEGER,
    ELAPSED_TIME_SEC INTEGER,
    TOTAL_ELEVATION_GAIN_METERS FLOAT,
    MAP_POLYLINE VARCHAR(16777216),
    AVERAGE_HEARTRATE FLOAT
);

-- Create the CHALLENGES table
CREATE OR REPLACE TABLE CHALLENGES (
    CHALLENGE_ID INTEGER,
    PARTNER_NAME VARCHAR(100),
    ATHLETE_ID INTEGER,
    JOIN_DATE TIMESTAMP,
    STATUS VARCHAR(50),
    PROGRESS_METERS FLOAT,
    IS_COMPLETE BOOLEAN,
    COMPLETION_DATE TIMESTAMP
);

-- Create the SUBSCRIPTIONS table
CREATE OR REPLACE TABLE SUBSCRIPTIONS (
    USER_ID INTEGER,
    SUBSCRIPTION_PLAN VARCHAR(50),
    PLAN_START_DATE TIMESTAMP,
    PLAN_END_DATE TIMESTAMP,
    IS_TRIAL BOOLEAN,
    LAST_FEATURE_USED VARCHAR(100),
    TOTAL_LOGINS_L30D INTEGER,
    CHURN_RISK_SCORE FLOAT
);

-- Grant permissions on tables to the role
GRANT ALL PRIVILEGES ON TABLE ACTIVITIES TO ROLE STRAVA_DEMO_ADMIN;
GRANT ALL PRIVILEGES ON TABLE CHALLENGES TO ROLE STRAVA_DEMO_ADMIN;
GRANT ALL PRIVILEGES ON TABLE SUBSCRIPTIONS TO ROLE STRAVA_DEMO_ADMIN;

-- Grant permissions on stage
GRANT ALL PRIVILEGES ON STAGE STRAVA_DEMO_STAGE TO ROLE STRAVA_DEMO_ADMIN;

-- Show completion message
SELECT 'Environment setup completed successfully!' as STATUS;