-- Finserv Payment Fraud Detection - ML Demo Environment Setup
-- This script sets up the complete environment for the finserv Fraud Demo

-- Set Context
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE ROLE FINSERV_DEMO_ADMIN;
GRANT ROLE FINSERV_DEMO_ADMIN TO ROLE ACCOUNTADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE FINSERV_DEMO_ADMIN;
GRANT USAGE ON WAREHOUSE STANDARD_WH_01_XS TO ROLE FINSERV_DEMO_ADMIN;

-- Switch to new role
USE ROLE FINSERV_DEMO_ADMIN;


USE WAREHOUSE STANDARD_WH_01_XS;

-- Create database
CREATE OR REPLACE DATABASE FINSERV_FRAUD_DEMO;

-- Create schema for raw data
CREATE OR REPLACE SCHEMA FINSERV_FRAUD_DEMO.RAW_DATA;

-- Switch to new context
USE DATABASE FINSERV_FRAUD_DEMO;
USE SCHEMA FINSERV_FRAUD_DEMO.RAW_DATA;

-- Create a file format for CSV files
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE;

-- Create an internal stage
CREATE OR REPLACE STAGE FINSERV_DEMO_STAGE
    FILE_FORMAT = CSV_FORMAT;

-- Create the CUSTOMERS table
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER,
    ACCOUNT_TIER VARCHAR(20),
    ACCOUNT_AGE_DAYS INTEGER,
    AVG_MONTHLY_SPEND FLOAT,
    NUM_LINKED_CARDS INTEGER
);

-- Create the MERCHANTS table
CREATE OR REPLACE TABLE MERCHANTS (
    MERCHANT_ID INTEGER,
    MERCHANT_NAME VARCHAR(100),
    MERCHANT_CATEGORY VARCHAR(50),
    COUNTRY_CODE VARCHAR(3),
    RISK_TIER VARCHAR(10)
);

-- Create the TRANSACTIONS table
CREATE OR REPLACE TABLE TRANSACTIONS (
    TRANSACTION_ID INTEGER,
    CUSTOMER_ID INTEGER,
    MERCHANT_ID INTEGER,
    AMOUNT FLOAT,
    MERCHANT_CATEGORY VARCHAR(50),
    COUNTRY_CODE VARCHAR(3),
    DEVICE_TYPE VARCHAR(30),
    CHANNEL VARCHAR(20),
    TRANSACTION_DATETIME TIMESTAMP,
    IS_FRAUD BOOLEAN
);

-- Grant permissions
GRANT ALL PRIVILEGES ON TABLE CUSTOMERS TO ROLE FINSERV_DEMO_ADMIN;
GRANT ALL PRIVILEGES ON TABLE MERCHANTS TO ROLE FINSERV_DEMO_ADMIN;
GRANT ALL PRIVILEGES ON TABLE TRANSACTIONS TO ROLE FINSERV_DEMO_ADMIN;
GRANT ALL PRIVILEGES ON STAGE FINSERV_DEMO_STAGE TO ROLE FINSERV_DEMO_ADMIN;

-- Create schemas for ML platform
CREATE SCHEMA IF NOT EXISTS FINSERV_FRAUD_DEMO.FINSERV_FEATURE_STORE;
CREATE SCHEMA IF NOT EXISTS FINSERV_FRAUD_DEMO.FINSERV_MODEL_REGISTRY;

-- Create persistent ML stage
CREATE OR REPLACE STAGE FINSERV_FRAUD_DEMO.FINSERV_MODEL_REGISTRY.ML_STAGE;

SELECT 'Environment setup completed successfully!' as STATUS;
